Repository f4pga/prjxray, pull requests merged in 2020-04, with the labels that each got.

#1287 htmlgen: use XRAY_ROI_TILEGRID instead of XRAY_ROI
  .github/kokoro/db-full.sh
  Makefile
  htmlgen/htmlgen.py
  htmlgen/htmlgen.sh
  settings/artix7_200t.sh
Labels: parts-infra, parts-tools

#1308 Re-enable IOI_ILOGIC[01]_CLKB.IOI_IMUX22_[01] pips.
  fuzzers/037-iob-pips/Makefile
  fuzzers/037-iob-pips/generate.tcl
  fuzzers/037-iob-pips/top.py
Labels: parts-fuzzers

#1313 xc7a100t support.
  Makefile
  fuzzers/074-dump_all/ignored_wires/artix7/xc7a100tfgg676-1_ignored_wires.txt
  settings/artix7_100t.sh
Labels: parts-docs, parts-fuzzers

#1315 Fix kokoro tarball packing
  .github/kokoro/db-full.sh
Labels: parts-fuzzers, parts-infra

#1316 python: add setup.py to allow installing prjxray libraries
  .gitignore
  setup.py
Labels: merge-if-green
